### PR TITLE
Fix: AAT v1 Support & Improvements (fixes: #20)

### LINKED ISSUE #20: Add support for authoring tool 1

### PR DESCRIPTION
**Pull request by joe-replin**
### Fixes
#20 
* Adds modern v1 Schema
* ES6 Conversion

#19 
* Adds support for data-order in navigation, schemas

#14
* Adjusts how the button appends

### Blockers
Unable to test within an AAT environment at this moment.

### CODE REVIEW

**Comment by joe-replin** [comment]
Tested and confirmed in AAT.

**Comment by swashbuck** [comment]
@joe-replin This all looks good.  Minor request:

Under Course Settings: Extensions, can you have it indented like Resources or Navigation?  So, you'd have a "Close" heading, and then show the nav order and close button (aria-label?) fields.  If you do this, change "Close button" to "ARIA label".

**Comment by joe-replin** [comment]
> @joe-replin This all looks good. Minor request:
> 
> Under Course Settings: Extensions, can you have it indented like Resources or Navigation? So, you'd have a "Close" heading, and then show the nav order and close button (aria-label?) fields. If you do this, change "Close button" to "ARIA label".

Additional child nesting behind a new title didn't work as planned. I wonder if titles at that level of nesting is supported. I was, however, able to create a title and nest the options at a parent level under the overall _globals extension but that isn't what we wanted. An overall UI cleanup needs to happen at a later date. In the meantime, I've added more descriptive UI field titles.

**Review by swashbuck — APPROVED** [review]
👍

**Pull request merged**
